config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'passwords',
    registrations: 'users',
    sessions: 'sessions',
  }

  get '/address', to: 'addresses#show', as: 'address'
  get '/info_window', to: 'info_window#index', as: 'info_window'
  get '/sitemap', to: 'sitemaps#index', as: 'sitemap'

  scope '/sidebar', controller: :sidebar do
    get :search, as: 'search'
    get :combo_form, as: 'combo_form'
    get :edit_profile, as: 'edit_profile'
  end

  resource :reminders
  resource :things
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  root to: 'main#index'
end

app/models/thing.rb
require 'open-uri'
require 'csv'

class Thing < ActiveRecord::Base
  acts_as_paranoid
  extend Forwardable
  include ActiveModel::ForbiddenAttributesProtection

  VALID_DRAIN_TYPES = ['Storm Drain', 'Storm Water Inlet Drain', 'Catch Basin Drain'].freeze

  belongs_to :user
  def_delegators :reverse_geocode, :city, :country, :country_code,
                 :full_address, :state, :street_address, :street_name,
                 :street_number, :zip
  has_many :reminders, dependent: :destroy
  validates :dr_asset_id, uniqueness: true, allow_nil: true
  validates :lat, presence: true
  validates :lng, presence: true
  validates :name, obscenity: true

  scope :adopted, -> { where.not(user_id: nil) }

  def self.find_closest(lat, lng, limit = 10)
    query = <<-SQL
      SELECT *, (3959 * ACOS(COS(RADIANS(?)) * COS(RADIANS(lat)) * COS(RADIANS(lng) - RADIANS(?)) + SIN(RADIANS(?)) * SIN(RADIANS(lat)))) AS distance
      FROM things
      WHERE deleted_at is NULL
      ORDER BY distance
      LIMIT ?
      SQL
    find_by_sql([query, lat.to_f, lng.to_f, lat.to_f, limit.to_i])
  end

  # People get to name their drains
  def display_name
    (adopted? ? adopted_name : name) || ''
  end

  def reverse_geocode
    @reverse_geocode ||= Geokit::Geocoders::MultiGeocoder.reverse_geocode([lat, lng])
  end

  def adopted?
    !user.nil?
  end

  # Link to more details about type of Thing
  #
  # Currently hardcoding since we only have one special case, but we should
  # move this into the database if we add an additional
  def detail_link
    return 'http://sfwater.org/index.aspx?page=399' if system_use_code == 'MS4'

    nil
  end

  def as_json(options = {})
    super({methods: [:display_name]}.merge(options))
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  respond_to :json

  def show
    @things = Thing.find_closest(params[:lat], params[:lng], params[:limit] || 10)
    if @things.blank?
      render(json: {errors: {address: [t('errors.not_found', thing: t('defaults.thing'))]}}, status: 404)
    else
      respond_with @things
    end
  end

  def update

    @thing = Thing.find(params[:id])

    if @thing.update_attributes(thing_params)

      send_adoption_email(@thing.user, @thing) if @thing.adopted?

      respond_with @thing

    else

      render(json: {errors: @thing.errors}, status: 500)
    end

  end

private

  def send_adoption_email(user, thing)
    case user.things.count
    when 1
      ThingMailer.first_adoption_confirmation(thing).deliver_later
    when 2
      ThingMailer.second_adoption_confirmation(thing).deliver_later
    end
  end

  def thing_params
    params.require(:thing).permit(:adopted_name, :user_id, :adopted_at)
  end
end

app/views/things/_abandon.html.haml
= form_for :thing, :url => things_path, :method => :put, :html => {:id => "abandon_form"} do |f|
  = f.hidden_field "id"
  = f.hidden_field "user_id", :value => ""
  = f.hidden_field "adopted_name", :value => ""
  %fieldset.form-group
    = f.submit t("buttons.abandon", :thing => t("defaults.thing")), :class => "btn btn-danger btn-block"

app/views/things/_jurisdiction.html.haml
%p
  = t("labels.discharges_to", :place => @thing.dr_discharge)
%p
  = t("labels.jurisdiction", :place => @thing.jurisdiction)

app/views/things/adopt.html.haml
%h2
  = t("titles.adopt", :thing => t("defaults.thing").titleize)
= form_for :thing, :url => things_path, :method => :put, :html => {:id => "adoption_form"} do |f|
  = f.hidden_field "id"
  = f.hidden_field "user_id", :value => current_user.id
  %fieldset.form-group
    = f.label "name", t("labels.name_thing", :thing => t("defaults.thing")), :id => "thing_name_label", :class => "control-label"
    = f.text_field "adopted_name", :value => @thing.name, :class => "form-control"
  %fieldset.form-group
    = f.submit t("buttons.adopt"), :class => "btn btn-primary btn-block"

  - unless @thing.detail_link.blank?
    %p
      %a{href: "#{@thing.detail_link}", target: '_blank'}
        = t("links.thing_details", :thing => t("defaults.thing"))

= render :partial => 'things/jurisdiction'