config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    passwords: 'passwords',
    registrations: 'users',
    sessions: 'sessions',
  }

  get '/address', to: 'addresses#show', as: 'address'
  get '/info_window', to: 'info_window#index', as: 'info_window'
  get '/sitemap', to: 'sitemaps#index', as: 'sitemap'

  scope '/sidebar', controller: :sidebar do
    get :search, as: 'search'
    get :combo_form, as: 'combo_form'
    get :edit_profile, as: 'edit_profile'
  end

  resource :reminders
  resource :things
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  root to: 'main#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :trackable, :validatable
  before_validation :remove_non_digits_from_phone_numbers
  has_many :reminders_from, class_name: 'Reminder', foreign_key: 'from_user_id', dependent: :destroy
  has_many :reminders_to, class_name: 'Reminder', foreign_key: 'to_user_id', dependent: :destroy
  has_many :things, dependent: :nullify
  validates :first_name, presence: true
  validates :last_name, presence: true, on: :create # requirement was added later, grandfather in users
  validates_formatting_of :email, using: :email
  validates_formatting_of :sms_number, using: :us_phone, allow_blank: true
  validates_formatting_of :voice_number, using: :us_phone, allow_blank: true
  validates_formatting_of :zip, using: :us_zip, allow_blank: true

  def remove_non_digits_from_phone_numbers
    self.sms_number = sms_number.to_s.gsub(/\D/, '').to_i if sms_number.present?
    self.voice_number = voice_number.to_s.gsub(/\D/, '').to_i if voice_number.present?
  end

  def name
    [first_name, last_name].reject(&:blank?).join(' ')
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  def edit
    render('sidebar/edit_profile', layout: 'sidebar')
  end

  def update

    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    if update_resource(resource, account_update_params)
      yield resource if block_given?
      # sign_in(resource_name, resource, bypass: true)
      sign_in(resource_name, resource, bypass_sign_in: true)
      flash[:notice] = 'Profile updated!'
      redirect_to(controller: 'sidebar', action: 'search')
    else
      clean_up_passwords(resource)
      render(json: {errors: resource.errors}, status: 500)
    end
  end

  def create
    build_resource(sign_up_params)
    if resource.save
      yield resource if block_given?
      sign_in(resource_name, resource)
      render(json: resource)
    else
      clean_up_passwords(resource)
      render(json: {errors: resource.errors}, status: 500)
    end
  end

private

  def sign_up_params
    params.require(:user).permit(:email, :first_name, :last_name, :organization, :password, :password_confirmation, :sms_number, :voice_number)
  end

  def account_update_params
    params.require(:user).permit(:address_1, :address_2, :city, :current_password, :email, :first_name, :last_name, :organization, :password, :password_confirmation, :remember_me, :sms_number, :state, :voice_number, :zip)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.haml
-# Note that this layout is used in adopt.html.haml as well 
%h4
  = t("titles.adopted", :thing_name => @thing.display_name != "" ? @thing.display_name.titleize : t("defaults.this_thing", :thing => t("defaults.thing")))
%div
  = t("titles.byline", :name => @thing.user.first_name)
  = t("titles.ofline", :organization => @thing.user.organization) unless @thing.user.organization.blank?
%br
= render :partial => 'things/jurisdiction'

app/views/users/_reminder.html.haml
= form_for :reminder, :url => reminders_path, :html => {:id => "reminder_form", :method => "post"} do |f|
  = f.hidden_field "from_user_id", :value => current_user.id
  = f.hidden_field "to_user_id", :value => @thing.user.id
  = f.hidden_field "thing_id", :value => @thing.id
  %fieldset.control-group
    = f.submit t("buttons.send_reminder"), :class => "btn"

app/views/users/adopted_thank_you.html.haml
%h2
  = t("titles.thank_you", thing: t("defaults.thing"))
%h2
  %a{ target: '_blank', href: "https://twitter.com/intent/tweet?text=#{URI.encode(t("titles.tweet_text", thing: t("defaults.thing")))}"}
    %i.fa.fa-twitter-square.fa-2x
  %a{ target: '_blank', href: "https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.adoptadrain-lgrow.org" }
    %i.fa.fa-facebook-square.fa-2x
  %a{ target: '_blank', href: "mailto:?subject=#{URI.encode(t('titles.main', thing: t('defaults.thing'), context: t('context.place') ))}&body=#{URI.encode(t('titles.email_text', context: t('context.place')))}" }
    %i.fa.fa-envelope-square.fa-2x
%hr
= render :partial => 'users/profile'
= render :partial => 'things/abandon'

app/views/users/profile.html.haml
= render :partial => 'users/profile'

app/views/users/sign_in.html.haml
%h3
  = t("titles.sign_in", :thing => t("defaults.thing"))
%a.guidelines{:href => "#guidelines", :"data-toggle" => "modal", :"data-target" => "#guidelines"}
  %p= t("links.learn_more", :thing => t("defaults.thing"))
= render :partial => 'things/jurisdiction'